name              "opscode-backup"
maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "Manages rsync based backups"
version           "1.1.3"
