name              "opscode-backup"
maintainer        "Chef Software, Inc."
maintainer_email  "cookbooks@chef.io"
license           "Apache 2.0"
description       "Manages rsync based backups"
version           "1.2.0"
